
resources:
  - name: app2
    type: GitRepo
    configuration:
      gitProvider: manishas_github
      path: manishas/app
      branches:
        include: master

pipelines:
  - name: barebones_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          nodePool: kermit_centos_pool
          inputResources:
            - name: app2
        execution:
          onExecute:
            - printenv

      - name: step_2
        type: Bash
        configuration:
          nodePool: kermit_centos_pool
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - printenv

      - name: step_3
        type: Bash
        configuration:
          nodePool: kermit_centos_pool
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - printenv

      - name: step_4
        type: Bash
        configuration:
          nodePool: kermit_centos_pool
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onExecute:
            - printenv
