
resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration  
      path: manishas/app    # replace with your repository name
      branches:
        include: master
        
  - name: msImage
    type: Image
    configuration:
      registry: ms_dh
      imageName: manishas/nightlyimage
      imageTag: latest
      autoPull: false        

pipelines:
  - name: barebones_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
          outputResources:
            - name: msImage
        execution:
          onExecute:
            - printenv
            - echo $res_myAppRepo_commitSha
            - add_run_variables first_stepid=$step_id
            - write_output msImage "imageTag=master" "sha=$commitSha" "description=\"hello world\""

      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: msImage
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid
            - echo $res_msImage_imageTag
            - echo $res_msImage_sha            
            - echo $res_msImage_description

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid


