
resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: manishas_github
      path: manishas/app
      branches:
        include: master

pipelines:
  - name: barebones_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - printenv
            - echo $res_myAppRepo_commitSha
            - add_run_variables first_stepid=$step_id

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Hello world"
            - echo $first_stepid

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onExecute:
            - echo $first_stepid
            - printenv
